# Buttons captions
START = 'Start'
HIT = 'Hit'
STAND = 'Stand'
QUIT = 'Quit'

# keys of data passing between modules
HIT_CARD = 'hit_card'
IMAGE = 'image'
SWITCHER = 'switcher'
CARD = 'card'
SPOT = 'spot'
PLAYER_NUM = 'player_num'
SHOW_MSG = 'show_message'
MSG = 'message'
IS_OVER = 'is_over'
DEALER_CARDS = 'dealer_cards'
DEALER_SPOTS = 'dealer_spots'
PLAYERS_CARDS = 'players_cards'
PLAYERS_SPOTS = 'players_spots'
PLAYERS = 'players'
NEW_GAME = 'new_game'

# view
TITLE = 'Blackjack-1.0'
DEALER = 'Dealer'
PLAYER = 'Player'
GEOMETRY = '1200x650'
GREEN = 'green'
BLUE = 'blue'
LOST = 'Lost'
TIE = 'Tie'
WON = 'Won'
SCORES = 'Scores'
